name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [test:e2e-local, test:e2e-remote]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: rm package-lock.json
    - run: npm install
    - run: npm test
    - name: Build project
      run: npm run build     
    - name: Test in browser
      uses: cypress-io/github-action@v6
      with:
        command: make ${{ matrix.test-type }}
    - name: Upload Cypress screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots-${{ matrix.test-type }}
        path: cypress/screenshots
